# === Common profile ============================================ ====
# ● Spring Boot common settings
spring:
  # Usage profile settings
  profiles:
    #Enable configuration file
    # ・ Specify the xxx part in "application-xxx.yml" of the same file
    active: local
  #Output settings
  output:
    ansi:
      #Enable / disable (never) / automate (detect) ANSI color output of console log ← Default setting
      # "Always" is forcibly displayed in color, but note that in the case of Windows, it will not be displayed in color unless "server / tool / ansicon / x64 / install.bat" is installed.
      enabled: always
# ● Log common settings
logging:
  #Log file path
  file: log/server.log